name: Deploy dataset

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *" # end of day everyday

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 14400
    runs-on: self-hosted
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3

      - name: Build pixz
        run: |
          wget "https://github.com/vasi/pixz/releases/download/v1.0.7/pixz-1.0.7.tar.gz"
          tar xf pixz-1.0.7.tar.gz
          cd pixz-1.0.7 || exit 1
          ./configure --prefix=$PWD/dist
          make -j $(nproc) && make install 
          TAR_XZ_COMMAND="tar -I $(readlink -f dist/bin/pixz) -xf"
          echo "Using TAR_XZ_COMMAND=$TAR_XZ_COMMAND"
          echo "TAR_XZ_COMMAND=${TAR_XZ_COMMAND}" >> $GITHUB_ENV

      - name: Build reactor
        run: sbt "project reactor; assembly"

      - name: Run reactor
        run: |
          export LD_LIBRARY_PATH="/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:${LD_LIBRARY_PATH:-}"
          export DATASET_PATH="$HOME/rtb-data/dataset-$(hostname)"
          export CACHE_PATH="$HOME/rtb-data/cache/$(uname -m)"

          echo "HOME=${HOME}" >> $GITHUB_ENV
          echo "DATASET_PATH=${DATASET_PATH}" >> $GITHUB_ENV
          echo "CACHE_PATH=${CACHE_PATH}" >> $GITHUB_ENV

          java -jar reactor/reactor.jar \
            --providers=gcc,llvm \
            --input=input/node33 \
            --output="$DATASET_PATH" \
            --cache="$CACHE_PATH" \
            --runner=local:node33.job

      - name: Publish page
        run: |
          sbt "project webapp; dist"
          cp -r "$DATASET_PATH" docs/dataset
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./docs"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
